# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'bankruptcyprevention_finalproject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for bankruptcyprevention_finalproject

pod 'BCryptSwift'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Core'
pod 'Firebase/Firestore'

end
